### ISSUE TITLE
Become unavailable when ON

### ISSUE THREAD

**Issue by stevencroft** [jnimmo/hass-intesisbox#12]
Hi,
Firstly thanks for creating this integration!

I've recently installed an intesisbox to my Fujitsu HVAC and functionally i can remotely control everything from HASS using your integration.

However when the HVAC unit is set to on from the HASS interface it shows as unavailable within HASS. Physically the unit is on and functioning its just the status in HASS.

Happy to provide logs, just let me know what you need?

![Screenshot_20210627-122802](https://user-images.githubusercontent.com/34257347/123532232-d96aad00-d74e-11eb-919a-9cc5f2cf8600.png)

**Comment by jbergler** [comment]
Hey @stevencroft does this still happen with the latest version?

If so, can you turn extra debugging on and share the logs please.

```
logger:
  default: info
  logs:
    custom_components.intesisbox: debug
    pyintesisbox: debug
```
