### ISSUE TITLE
min_temp/max_temp values 1/10th of actual values

### ISSUE THREAD

**Issue by AtticusG3** [jnimmo/hass-intesisbox#28]
Component sets min temp and max temp to 1.6 adn 3.2 degree's instead of 16 and 32 degrees

min_temp: 1.6
max_temp: 3.2

![image](https://user-images.githubusercontent.com/5202607/206865110-782a1286-48c7-49ef-897c-763eef03d433.png)

Device info
MH-RC-WMP-1
by Intesis
Firmware: v1.3.3

IntensisHome Component says "An unkown error occurred." when trying to setup IntensisHome custom Component

**Comment by jbergler** [comment]
Could you turn on debugging for both the component and the underlying library please? 
The logs should then include the full conversation which will help debug this.

```
logger:
  logs:
    custom_components.intesisbox: debug
    pyintesisbox: debug
```
